summary_task:
  description: >
    Given the traffic dataset, analyze congestion levels, accident reports, 
    and peak traffic patterns to generate a summary.
    {data}
  expected_output: >
    A detailed report summarizing the traffic situation, including congestion hotspots, 
    accident-prone areas, and peak traffic times. The report should be in markdown format.
  agent: traffic_summarizer

planning_task:
  description: >
    Using the traffic summary, create an actionable traffic management plan, 
    proposing measures to optimize road use and reduce congestion.
  expected_output: >
    A comprehensive traffic management plan outlining strategies to alleviate congestion, 
    improve traffic flow, and enhance road safety. The plan should be in markdown format.
  agent: traffic_planner
