summary_task:
    description: >
        Given the traffic dataset, analyze congestion levels, accident reports, 
        and peak traffic patterns to generate a summary.
        At the end of the summary, using this traffic summary, create an actionable traffic management plan, 
        proposing measures to optimize road use and reduce congestion.
        {data}
    expected_output: >
        A detailed report summarizing the traffic situation, including congestion hotspots, 
        accident-prone areas, and peak traffic times and comprehensive actionable traffic management plan outlining real time strategies to alleviate congestion, 
        improve traffic flow, and enhance road safety.
        Formatted as markdown without '```'
    agent: traffic_summarizer
    output_file: summary.md

planning_task:
    description: >
        Using the traffic summary, create an actionable traffic management plan, 
        proposing measures to optimize road use and reduce congestion.
    expected_output: >
        A comprehensive traffic management plan outlining strategies to alleviate congestion, 
        improve traffic flow, and enhance road safety.
        Formatted as markdown without '```'
    agent: traffic_planner
    output_file: plan.md
