create type "public"."status" as enum ('PENDING', 'COMPLETED');

create table "public"."generated_summary" (
    "id" bigint generated by default as identity not null,
    "summary" text,
    "status" status not null default 'PENDING'::status,
    "created_at" timestamp with time zone not null default now()
);


CREATE UNIQUE INDEX generated_summary_pkey ON public.generated_summary USING btree (id);

alter table "public"."generated_summary" add constraint "generated_summary_pkey" PRIMARY KEY using index "generated_summary_pkey";

grant delete on table "public"."generated_summary" to "anon";

grant insert on table "public"."generated_summary" to "anon";

grant references on table "public"."generated_summary" to "anon";

grant select on table "public"."generated_summary" to "anon";

grant trigger on table "public"."generated_summary" to "anon";

grant truncate on table "public"."generated_summary" to "anon";

grant update on table "public"."generated_summary" to "anon";

grant delete on table "public"."generated_summary" to "authenticated";

grant insert on table "public"."generated_summary" to "authenticated";

grant references on table "public"."generated_summary" to "authenticated";

grant select on table "public"."generated_summary" to "authenticated";

grant trigger on table "public"."generated_summary" to "authenticated";

grant truncate on table "public"."generated_summary" to "authenticated";

grant update on table "public"."generated_summary" to "authenticated";

grant delete on table "public"."generated_summary" to "service_role";

grant insert on table "public"."generated_summary" to "service_role";

grant references on table "public"."generated_summary" to "service_role";

grant select on table "public"."generated_summary" to "service_role";

grant trigger on table "public"."generated_summary" to "service_role";

grant truncate on table "public"."generated_summary" to "service_role";

grant update on table "public"."generated_summary" to "service_role";


