[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12, <3.13"
dependencies = [
    "crewai>=0.105.0",
    "crewai-tools>=0.38.0",
    "fastapi[standard]>=0.115.11",
]
